const LEAGUE_NAMES = [
  "Neon Apex League",
  "Turbo Canal Cup",
  "Voltage Derby",
  "Night Grid Series",
  "Harbor Dash Club",
  "Pulse Circuit League",
  "Metro Sprint Cup",
  "Rainline Racing",
  "Switchback Trophy",
  "Skyline GP Club",
  "Dockside Duel",
  "Rapid Loop League",
  "Battery Row Cup",
  "Overtake Society",
  "Storm Brake Series",
  "Gridlight Trophy",
  "Urban Torque Cup",
  "Pitlane Rebels",
  "Charge Point League",
  "Curbside Classic",
  "Final Lap Union",
  "Pocket Rocket Cup",
  "Apex Signal League",
  "Wetline Challenge",
  "Short Track Syndicate",
  "Tarmac Voltage Cup",
  "Late Brake League",
  "Slipstream Social",
  "Greenlight Rally",
  "City Pulse GP",
  "Micro Sprint League",
  "Rooftop Racing Cup",
  "Crosswalk Clash",
  "Rain Mode Series",
  "Fast Lane Foundry",
  "Midnight Sector Cup",
  "Boost Bay League",
  "Gridlock Grand Prix",
  "Relay Racing Club",
  "Torque Alley Cup",
  "Terminal Sprint",
  "Canal Charge Series",
  "Sharp Corner League",
  "Downtown Draft Cup",
  "Switchyard GP",
  "Last Meter League",
  "Flashpoint Trophy",
  "Signal Sprint Cup",
  "Inner Ring Series",
  "Metro Apex Club"
];

const TEAM_NAMES = [
  "Volt Union",
  "Late Apex",
  "Mika Blitz",
  "Atlas Works",
  "Red Peak",
  "Northline",
  "Neon Torque",
  "Rain Pulse",
  "Grid Saints",
  "Turbo Pals",
  "Battery Bandits",
  "Pit Wall Kids",
  "Curb Riders",
  "Signal Chasers",
  "Dock Dash",
  "Apex Snacks",
  "Blue Boost",
  "Rapid Sparks",
  "Storm Mode",
  "Pixel Pistons",
  "Tarmac Toast",
  "Metro Sparks",
  "Corner Kings",
  "Charge Pirates",
  "Brake Works",
  "Slipstream Crew",
  "Tiny Rockets",
  "Wetline Works",
  "Turbo Turns",
  "Dash Mechanics",
  "Skyline Sprinters",
  "Pocket Bolts",
  "Final Lap Labs",
  "Urban Comets",
  "Relay Rebels",
  "Boost Bureau",
  "Night Pistons",
  "Harbor Hype",
  "Greenlight Gang",
  "Switchback Stars",
  "Rainy Racers",
  "Torque Tacos",
  "Fast Lane Flash",
  "Micro Mavericks",
  "Apex Arcade",
  "Grid Gliders",
  "Voltage Vibes",
  "Canal Crew",
  "Sector Sparks",
  "Drift Donuts"
];

export function randomLeagueName() {
  return pick(LEAGUE_NAMES);
}

export function randomTeamName() {
  return pick(TEAM_NAMES);
}

function pick(values: string[]) {
  return values[Math.floor(Math.random() * values.length)] ?? values[0] ?? "";
}
