export const TEAM_NAME_SUGGESTIONS = [
  "Volt Union",
  "Late Apex",
  "Mika Blitz",
  "Atlas Works",
  "Red Peak",
  "Northline",
  "Neon Torque",
  "Rain Pulse",
  "Grid Saints",
  "Turbo Pals",
  "Battery Bandits",
  "Pit Wall Kids",
  "Curb Riders",
  "Signal Chasers",
  "Dock Dash",
  "Apex Snacks",
  "Blue Boost",
  "Rapid Sparks",
  "Storm Mode",
  "Pixel Pistons",
  "Tarmac Toast",
  "Metro Sparks",
  "Corner Kings",
  "Charge Pirates",
  "Brake Works",
  "Slipstream Crew",
  "Tiny Rockets",
  "Wetline Works",
  "Turbo Turns",
  "Dash Mechanics",
  "Skyline Sprinters",
  "Pocket Bolts",
  "Final Lap Labs",
  "Urban Comets",
  "Relay Rebels",
  "Boost Bureau",
  "Night Pistons",
  "Harbor Hype",
  "Greenlight Gang",
  "Switchback Stars",
  "Rainy Racers",
  "Torque Tacos",
  "Fast Lane Flash",
  "Micro Mavericks",
  "Apex Arcade",
  "Grid Gliders",
  "Voltage Vibes",
  "Canal Crew",
  "Sector Sparks",
  "Drift Donuts",
  "Apex Foundry",
  "Blackline GP",
  "Blue Harpoon",
  "Brake Point",
  "Carbon Yard",
  "Circuit Nord",
  "Coastal Apex",
  "Copperline",
  "Corsa Nova",
  "Delta Forge",
  "Drift Union",
  "Eagle Run",
  "Eastbound",
  "Falcon Works",
  "Fastlane",
  "Ferro Racing",
  "Grid Seven",
  "Harbor Sprint",
  "Helio Corse",
  "Iron Pulse",
  "Jetstream",
  "Kerbside",
  "Lane Eight",
  "Lunar Apex",
  "Metro Veloce",
  "Midnight GP",
  "Monarch Racing",
  "Neon Sector",
  "Northstar",
  "Nova Lane",
  "Omega Works",
  "Orbit Corse",
  "Pacific Line",
  "Piston Club",
  "Polecraft",
  "Quantum GP",
  "Rapid Vale",
  "Redshift",
  "Ridge Motors",
  "Silverline",
  "Skyline Works",
  "Slipstream",
  "South Gate",
  "Steel Apex",
  "Stormline",
  "Summit Corse",
  "Torque House",
  "Union Brake",
  "Vector Lane",
  "Westline"
] as const;
