ALTER TABLE "leagues" ADD COLUMN "maxPlayers" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "leagues" ADD COLUMN "fillWithBots" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "leagues" ADD COLUMN "qualifyingAttemptLimit" INTEGER NOT NULL DEFAULT 3;
